// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABRIawTinEarI0yCehUR8qt2WMsB03elg',
    appId: '1:1096226607310:web:3680a7b7b5bcfbef77009f',
    messagingSenderId: '1096226607310',
    projectId: 'phoneauth-e6e57',
    authDomain: 'phoneauth-e6e57.firebaseapp.com',
    storageBucket: 'phoneauth-e6e57.appspot.com',
    measurementId: 'G-N455JMF58S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSayGhkQLs51khA68J_2nApv1pPLJXfLk',
    appId: '1:1096226607310:android:fb2cde750c45486377009f',
    messagingSenderId: '1096226607310',
    projectId: 'phoneauth-e6e57',
    storageBucket: 'phoneauth-e6e57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFuLEgmQOlBmyzKxZGC9AembvUmErZrls',
    appId: '1:1096226607310:ios:3a534fc79383f8b377009f',
    messagingSenderId: '1096226607310',
    projectId: 'phoneauth-e6e57',
    storageBucket: 'phoneauth-e6e57.appspot.com',
    iosBundleId: 'com.rrdhoi.eventapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFuLEgmQOlBmyzKxZGC9AembvUmErZrls',
    appId: '1:1096226607310:ios:805594105712074c77009f',
    messagingSenderId: '1096226607310',
    projectId: 'phoneauth-e6e57',
    storageBucket: 'phoneauth-e6e57.appspot.com',
    iosBundleId: 'com.rrdhoi.eventappSwoc.RunnerTests',
  );
}
